// Empire-centric mocked data. Each empire is a first-class object whose
// `territory` lists the MODERN countries its historical extent roughly covered
// (approximated to present-day borders from the world-atlas dataset). The app
// inverts this into a country -> empires index for hover, and paints the whole
// territory when an empire is active on the timeline or focused via search.
//
// Fields:
//   id        : stable slug
//   name, era : display
//   start,end : numeric years (negative = BC) — drive the timeline
//   blurb     : one-line description
//   capital   : { name, coords:[lng,lat] } — famous seat of power (map marker)
//   territory : [modern country names as they appear in countries-110m]
//
// Country names must match the dataset exactly (validated at build time).
window.EMPIRES = [
  // ---- Mesopotamia & the Near East ----
  { id: "sumer", name: "Sumer", era: "c. 4500–1900 BC", start: -4500, end: -1900,
    blurb: "The first cities — Ur, Uruk — and the birth of writing on clay.",
    capital: { name: "Uruk", coords: [45.64, 31.32] }, territory: ["Iraq"] },
  { id: "babylon", name: "Babylon", era: "c. 1894–539 BC", start: -1894, end: -539,
    blurb: "Hammurabi's law and the fabled Hanging Gardens along the Euphrates.",
    capital: { name: "Babylon", coords: [44.42, 32.54] }, territory: ["Iraq"] },
  { id: "assyria", name: "Assyria", era: "c. 2500–609 BC", start: -2500, end: -609,
    blurb: "Iron-fisted empire ruling from mighty Nineveh.",
    capital: { name: "Nineveh", coords: [43.15, 36.36] }, territory: ["Iraq", "Syria"] },
  { id: "achaemenid", name: "Achaemenid Persia", era: "550–330 BC", start: -550, end: -330,
    blurb: "Cyrus and Darius forged history's first great multinational empire.",
    capital: { name: "Persepolis", coords: [52.89, 29.94] },
    territory: ["Iran", "Iraq", "Turkey", "Syria", "Lebanon", "Israel", "Jordan", "Egypt", "Afghanistan", "Pakistan", "Uzbekistan", "Turkmenistan", "Armenia", "Azerbaijan", "Cyprus"] },
  { id: "parthia", name: "Parthia", era: "247 BC–224 AD", start: -247, end: 224,
    blurb: "Horse-archers who checked the legions of Rome.",
    capital: { name: "Hecatompylos", coords: [54.0, 36.14] },
    territory: ["Iran", "Iraq", "Armenia", "Turkmenistan", "Azerbaijan"] },
  { id: "sassanid", name: "Sassanid Empire", era: "224–651 AD", start: 224, end: 651,
    blurb: "The last pre-Islamic Persian dynasty, rival of Byzantium.",
    capital: { name: "Firuzabad", coords: [52.58, 28.84] },
    territory: ["Iran", "Iraq", "Armenia", "Azerbaijan", "Afghanistan", "Turkmenistan"] },
  { id: "umayyad", name: "Umayyad Caliphate", era: "661–750 AD", start: 661, end: 750,
    blurb: "First great Islamic dynasty, its realm stretching from Spain to India.",
    capital: { name: "Damascus", coords: [36.29, 33.51] },
    territory: ["Syria", "Iraq", "Iran", "Israel", "Jordan", "Lebanon", "Egypt", "Saudi Arabia", "Yemen", "Oman", "Libya", "Tunisia", "Algeria", "Morocco", "Spain", "Portugal", "Afghanistan", "Pakistan", "Uzbekistan", "Turkmenistan", "Armenia", "Azerbaijan"] },

  // ---- Anatolia ----
  { id: "hittite", name: "Hittite Empire", era: "c. 1600–1180 BC", start: -1600, end: -1180,
    blurb: "Bronze-age power of Anatolia, rival of Egypt at Kadesh.",
    capital: { name: "Hattusa", coords: [34.61, 40.02] }, territory: ["Turkey", "Syria"] },
  { id: "byzantine", name: "Byzantine Empire", era: "330–1453 AD", start: 330, end: 1453,
    blurb: "Constantinople, the Christian heir of Rome in the East.",
    capital: { name: "Constantinople", coords: [28.98, 41.01] },
    territory: ["Turkey", "Greece", "Bulgaria", "Cyprus", "Albania", "Macedonia", "Serbia"] },
  { id: "ottoman", name: "Ottoman Empire", era: "1299–1922 AD", start: 1299, end: 1922,
    blurb: "Six centuries astride three continents.",
    capital: { name: "Istanbul", coords: [28.98, 41.01] },
    territory: ["Turkey", "Greece", "Bulgaria", "Egypt", "Syria", "Iraq", "Israel", "Jordan", "Lebanon", "Saudi Arabia", "Serbia", "Bosnia and Herz.", "Albania", "Macedonia", "Romania", "Hungary", "Algeria", "Tunisia", "Libya", "Yemen", "Cyprus", "Armenia", "Georgia", "Moldova", "Kosovo", "Montenegro", "Croatia"] },

  // ---- North & Sub-Saharan Africa ----
  { id: "egypt", name: "Ancient Egypt", era: "c. 3100–332 BC", start: -3100, end: -332,
    blurb: "Pharaohs, pyramids, and the gift of the Nile.",
    capital: { name: "Thebes", coords: [32.64, 25.70] }, territory: ["Egypt"] },
  { id: "ptolemaic", name: "Ptolemaic Kingdom", era: "305–30 BC", start: -305, end: -30,
    blurb: "Greek dynasty of Alexandria, ending with Cleopatra VII.",
    capital: { name: "Alexandria", coords: [29.92, 31.20] }, territory: ["Egypt", "Cyprus"] },
  { id: "kush", name: "Kingdom of Kush", era: "c. 1070 BC–350 AD", start: -1070, end: 350,
    blurb: "Nubian pharaohs and the steep pyramids of Meroë.",
    capital: { name: "Meroë", coords: [33.72, 16.93] }, territory: ["Sudan"] },
  { id: "aksum", name: "Kingdom of Aksum", era: "c. 100–940 AD", start: 100, end: 940,
    blurb: "Trading empire of towering stelae and early coinage.",
    capital: { name: "Aksum", coords: [38.72, 14.13] }, territory: ["Ethiopia", "Eritrea"] },
  { id: "ethiopia", name: "Ethiopian Empire", era: "1270–1974 AD", start: 1270, end: 1974,
    blurb: "The Solomonic dynasty and the rock churches of Lalibela.",
    capital: { name: "Gondar", coords: [37.47, 12.60] }, territory: ["Ethiopia", "Eritrea"] },
  { id: "carthage", name: "Carthage", era: "c. 814–146 BC", start: -814, end: -146,
    blurb: "Hannibal's maritime empire, Rome's great rival.",
    capital: { name: "Carthage", coords: [10.32, 36.85] },
    territory: ["Tunisia", "Algeria", "Libya", "Spain", "Morocco"] },
  { id: "numidia", name: "Numidia", era: "202–46 BC", start: -202, end: -46,
    blurb: "Kingdom of the Berber cavalry masters, Masinissa's realm.",
    capital: { name: "Cirta", coords: [6.61, 36.36] }, territory: ["Algeria"] },
  { id: "almoravid", name: "Almoravid Dynasty", era: "1040–1147 AD", start: 1040, end: 1147,
    blurb: "Veiled Berber horsemen who founded Marrakesh.",
    capital: { name: "Marrakesh", coords: [-7.99, 31.63] },
    territory: ["Morocco", "Spain", "Portugal", "Mauritania", "Algeria"] },
  { id: "almohad", name: "Almohad Caliphate", era: "1121–1269 AD", start: 1121, end: 1269,
    blurb: "Reformist empire spanning North Africa and Iberia.",
    capital: { name: "Marrakesh", coords: [-7.99, 31.63] },
    territory: ["Morocco", "Spain", "Portugal", "Algeria", "Tunisia"] },
  { id: "ghana", name: "Ghana Empire", era: "c. 300–1240 AD", start: 300, end: 1240,
    blurb: "The 'Land of Gold' that anchored the trans-Saharan trade.",
    capital: { name: "Koumbi Saleh", coords: [-7.5, 15.77] }, territory: ["Mali", "Mauritania"] },
  { id: "mali", name: "Mali Empire", era: "1235–1670 AD", start: 1235, end: 1670,
    blurb: "Mansa Musa's golden pilgrimage and the schools of Timbuktu.",
    capital: { name: "Timbuktu", coords: [-3.0, 16.77] },
    territory: ["Mali", "Mauritania", "Senegal", "Guinea", "Gambia"] },
  { id: "benin", name: "Benin Empire", era: "1180–1897 AD", start: 1180, end: 1897,
    blurb: "City of bronze plaques and mighty earthen walls.",
    capital: { name: "Benin City", coords: [5.62, 6.34] }, territory: ["Nigeria"] },
  { id: "oyo", name: "Oyo Empire", era: "c. 1300–1896 AD", start: 1300, end: 1896,
    blurb: "Yoruba cavalry power of the West African savanna.",
    capital: { name: "Oyo-Ile", coords: [4.32, 8.9] }, territory: ["Nigeria", "Benin"] },
  { id: "ashanti", name: "Ashanti Empire", era: "1701–1957 AD", start: 1701, end: 1957,
    blurb: "The Golden Stool and a fierce resistance to empire.",
    capital: { name: "Kumasi", coords: [-1.62, 6.69] }, territory: ["Ghana"] },
  { id: "zimbabwe", name: "Kingdom of Zimbabwe", era: "c. 1220–1450 AD", start: 1220, end: 1450,
    blurb: "The great drystone walls of Great Zimbabwe.",
    capital: { name: "Great Zimbabwe", coords: [30.93, -20.27] }, territory: ["Zimbabwe"] },
  { id: "mutapa", name: "Kingdom of Mutapa", era: "c. 1430–1760 AD", start: 1430, end: 1760,
    blurb: "Gold-trading realm that awed Portuguese visitors.",
    capital: { name: "Mutapa", coords: [31.9, -16.7] }, territory: ["Zimbabwe", "Mozambique"] },

  // ---- Europe ----
  { id: "minoan", name: "Minoan Crete", era: "c. 3000–1100 BC", start: -3000, end: -1100,
    blurb: "Europe's first advanced civilization, palace of Knossos.",
    capital: { name: "Knossos", coords: [25.16, 35.30] }, territory: ["Greece"] },
  { id: "greece", name: "Classical Greece", era: "c. 500–323 BC", start: -500, end: -323,
    blurb: "Athens, Sparta, and the cradle of democracy and philosophy.",
    capital: { name: "Athens", coords: [23.73, 37.98] }, territory: ["Greece", "Cyprus"] },
  { id: "macedon", name: "Macedonian Empire", era: "336–323 BC", start: -336, end: -323,
    blurb: "Alexander the Great's conquests from Greece to the Indus.",
    capital: { name: "Pella", coords: [22.52, 40.76] },
    territory: ["Greece", "Macedonia", "Turkey", "Egypt", "Israel", "Lebanon", "Syria", "Jordan", "Iraq", "Iran", "Afghanistan", "Pakistan", "Uzbekistan", "Turkmenistan", "Tajikistan", "Cyprus", "Armenia"] },
  { id: "etruscan", name: "Etruscan Civilization", era: "c. 900–100 BC", start: -900, end: -100,
    blurb: "Enigmatic culture that shaped early Rome.",
    capital: { name: "Tarquinia", coords: [11.76, 42.25] }, territory: ["Italy"] },
  { id: "rome", name: "Roman Empire", era: "509 BC–476 AD", start: -509, end: 476,
    blurb: "From the seven hills to an empire encircling the Mediterranean.",
    capital: { name: "Rome", coords: [12.49, 41.89] },
    territory: ["Italy", "Spain", "Portugal", "France", "United Kingdom", "Greece", "Turkey", "Egypt", "Syria", "Israel", "Jordan", "Lebanon", "Tunisia", "Algeria", "Morocco", "Libya", "Switzerland", "Austria", "Croatia", "Serbia", "Bulgaria", "Romania", "Belgium", "Albania", "Macedonia", "Slovenia", "Cyprus"] },
  { id: "hispania", name: "Roman Hispania", era: "218 BC–472 AD", start: -218, end: 472,
    blurb: "Rome's rich Iberian province, birthplace of emperors.",
    capital: { name: "Tarraco", coords: [1.25, 41.12] }, territory: ["Spain", "Portugal"] },
  { id: "gaul", name: "Gaul", era: "c. 500 BC–50 BC", start: -500, end: -50,
    blurb: "Celtic tribes and Vercingetorix's last stand against Caesar.",
    capital: { name: "Alesia", coords: [4.5, 47.54] },
    territory: ["France", "Belgium", "Luxembourg", "Switzerland"] },
  { id: "carolingian", name: "Carolingian Empire", era: "800–888 AD", start: 800, end: 888,
    blurb: "Charlemagne crowned emperor, reviving the West.",
    capital: { name: "Aachen", coords: [6.08, 50.78] },
    territory: ["France", "Germany", "Belgium", "Netherlands", "Switzerland", "Austria", "Luxembourg", "Italy"] },
  { id: "hre", name: "Holy Roman Empire", era: "800–1806 AD", start: 800, end: 1806,
    blurb: "A thousand-year patchwork of the German lands.",
    capital: { name: "Aachen", coords: [6.08, 50.78] },
    territory: ["Germany", "Austria", "Czechia", "Switzerland", "Netherlands", "Belgium", "Luxembourg", "Slovenia", "Italy"] },
  { id: "napoleon", name: "First French Empire", era: "1804–1815 AD", start: 1804, end: 1815,
    blurb: "Napoleon's eagles marched across a continent.",
    capital: { name: "Paris", coords: [2.35, 48.86] },
    territory: ["France", "Belgium", "Netherlands", "Luxembourg", "Italy", "Switzerland", "Germany"] },
  { id: "prussia", name: "Kingdom of Prussia", era: "1701–1918 AD", start: 1701, end: 1918,
    blurb: "Disciplined Prussian power that forged modern Germany.",
    capital: { name: "Berlin", coords: [13.40, 52.52] }, territory: ["Germany", "Poland"] },
  { id: "spanish", name: "Spanish Empire", era: "1492–1898 AD", start: 1492, end: 1898,
    blurb: "Galleons, gold, and a realm spanning the New World.",
    capital: { name: "Seville", coords: [-5.98, 37.39] },
    territory: ["Spain", "Mexico", "Guatemala", "Cuba", "Colombia", "Peru", "Bolivia", "Ecuador", "Venezuela", "Chile", "Argentina", "Paraguay", "Panama", "Philippines", "Dominican Rep."] },
  { id: "british", name: "British Empire", era: "1583–1997 AD", start: 1583, end: 1997,
    blurb: "The empire on which the sun never set.",
    capital: { name: "London", coords: [-0.13, 51.51] },
    territory: ["United Kingdom", "Ireland", "India", "Pakistan", "Bangladesh", "Myanmar", "South Africa", "Egypt", "Nigeria", "Kenya", "Canada", "Australia", "New Zealand", "Sri Lanka", "Malaysia", "Ghana", "Sudan"] },

  // ---- Russia & the Steppe ----
  { id: "scythia", name: "Scythia", era: "c. 700 BC–300 AD", start: -700, end: 300,
    blurb: "Golden-worked horse nomads of the Pontic steppe.",
    capital: { name: "Kamianka", coords: [34.6, 47.5] },
    territory: ["Ukraine", "Russia", "Kazakhstan"] },
  { id: "kievan", name: "Kievan Rus'", era: "882–1240 AD", start: 882, end: 1240,
    blurb: "Medieval federation that seeded Russia, Ukraine, and Belarus.",
    capital: { name: "Kyiv", coords: [30.52, 50.45] }, territory: ["Ukraine", "Belarus", "Russia"] },
  { id: "tsardom", name: "Tsardom of Russia", era: "1547–1721 AD", start: 1547, end: 1721,
    blurb: "Ivan the Terrible and the rise of Moscow.",
    capital: { name: "Moscow", coords: [37.62, 55.75] }, territory: ["Russia"] },
  { id: "russian", name: "Russian Empire", era: "1721–1917 AD", start: 1721, end: 1917,
    blurb: "Peter and Catherine's realm from Poland to the Pacific.",
    capital: { name: "St. Petersburg", coords: [30.31, 59.94] },
    territory: ["Russia", "Finland", "Ukraine", "Belarus", "Lithuania", "Latvia", "Estonia", "Georgia", "Armenia", "Azerbaijan", "Kazakhstan", "Uzbekistan", "Turkmenistan", "Kyrgyzstan", "Tajikistan", "Moldova", "Poland"] },
  { id: "ussr", name: "Soviet Union", era: "1922–1991 AD", start: 1922, end: 1991,
    blurb: "The USSR — fifteen republics from the Baltic to the Bering Strait.",
    capital: { name: "Moscow", coords: [37.62, 55.75] },
    territory: ["Russia", "Ukraine", "Belarus", "Kazakhstan", "Uzbekistan", "Turkmenistan", "Kyrgyzstan", "Tajikistan", "Georgia", "Armenia", "Azerbaijan", "Lithuania", "Latvia", "Estonia", "Moldova"] },
  { id: "mongol", name: "Mongol Empire", era: "1206–1368 AD", start: 1206, end: 1368,
    blurb: "Genghis Khan built the largest contiguous land empire in history.",
    capital: { name: "Karakorum", coords: [102.83, 47.20] },
    territory: ["Mongolia", "China", "Russia", "Kazakhstan", "Kyrgyzstan", "Uzbekistan", "Turkmenistan", "Tajikistan", "Iran", "Iraq", "Afghanistan", "Ukraine", "Belarus", "Georgia", "Armenia", "Azerbaijan", "North Korea"] },
  { id: "xiongnu", name: "Xiongnu Confederation", era: "c. 209 BC–100 AD", start: -209, end: 100,
    blurb: "Steppe nomad power that pressed on Han China.",
    capital: { name: "Ordu-Baliq", coords: [102.66, 47.42] }, territory: ["Mongolia", "Kazakhstan"] },
  { id: "timurid", name: "Timurid Empire", era: "1370–1507 AD", start: 1370, end: 1507,
    blurb: "Tamerlane's conquests and the blue domes of Samarkand.",
    capital: { name: "Samarkand", coords: [66.98, 39.65] },
    territory: ["Uzbekistan", "Iran", "Afghanistan", "Turkmenistan", "Tajikistan", "Pakistan"] },
  { id: "sogdiana", name: "Sogdiana", era: "c. 500 BC–722 AD", start: -500, end: 722,
    blurb: "Silk Road merchants whose caravans linked China and Rome.",
    capital: { name: "Samarkand", coords: [66.98, 39.65] }, territory: ["Uzbekistan", "Tajikistan"] },

  // ---- South & Central Asia ----
  { id: "indus", name: "Indus Valley Civilization", era: "c. 2600–1900 BC", start: -2600, end: -1900,
    blurb: "Planned brick cities with drains before most of the world had walls.",
    capital: { name: "Mohenjo-daro", coords: [68.14, 27.33] }, territory: ["Pakistan", "India"] },
  { id: "maurya", name: "Maurya Empire", era: "322–185 BC", start: -322, end: -185,
    blurb: "Ashoka the Great spread Buddhism across the subcontinent.",
    capital: { name: "Pataliputra", coords: [85.14, 25.61] },
    territory: ["India", "Pakistan", "Bangladesh", "Nepal", "Afghanistan"] },
  { id: "gupta", name: "Gupta Empire", era: "c. 320–550 AD", start: 320, end: 550,
    blurb: "A classical golden age of science, art, and mathematics.",
    capital: { name: "Ujjain", coords: [75.78, 23.18] }, territory: ["India", "Bangladesh", "Nepal"] },
  { id: "mughal", name: "Mughal Empire", era: "1526–1857 AD", start: 1526, end: 1857,
    blurb: "The Taj Mahal and a court of extraordinary splendor.",
    capital: { name: "Agra", coords: [78.04, 27.18] },
    territory: ["India", "Pakistan", "Bangladesh", "Afghanistan"] },
  { id: "gandhara", name: "Gandhara", era: "c. 500 BC–1000 AD", start: -500, end: 1000,
    blurb: "Where Greek sculpture met the Buddha at Taxila.",
    capital: { name: "Taxila", coords: [72.82, 33.74] }, territory: ["Pakistan", "Afghanistan"] },
  { id: "kushan", name: "Kushan Empire", era: "c. 30–375 AD", start: 30, end: 375,
    blurb: "Silk Road crossroads blending Greek, Persian, and Indian worlds.",
    capital: { name: "Balkh", coords: [66.9, 36.76] },
    territory: ["Afghanistan", "Pakistan", "Uzbekistan", "Tajikistan", "India"] },
  { id: "ghaznavid", name: "Ghaznavid Empire", era: "977–1186 AD", start: 977, end: 1186,
    blurb: "A Turkic power whose armies reached deep into India.",
    capital: { name: "Ghazni", coords: [68.42, 33.55] },
    territory: ["Afghanistan", "Pakistan", "Iran", "Turkmenistan"] },

  // ---- East & Southeast Asia ----
  { id: "qin", name: "Qin Dynasty", era: "221–206 BC", start: -221, end: -206,
    blurb: "First unified empire, the Great Wall, the Terracotta Army.",
    capital: { name: "Xianyang", coords: [108.71, 34.33] }, territory: ["China"] },
  { id: "han", name: "Han Dynasty", era: "206 BC–220 AD", start: -206, end: 220,
    blurb: "Golden age that gave its name to the Chinese people.",
    capital: { name: "Chang'an", coords: [108.94, 34.34] },
    territory: ["China", "North Korea", "Vietnam"] },
  { id: "tang", name: "Tang Dynasty", era: "618–907 AD", start: 618, end: 907,
    blurb: "Cosmopolitan zenith of poetry, silk, and the open road.",
    capital: { name: "Chang'an", coords: [108.94, 34.34] }, territory: ["China", "Vietnam"] },
  { id: "heian", name: "Heian Japan", era: "794–1185 AD", start: 794, end: 1185,
    blurb: "Courtly Kyoto and The Tale of Genji.",
    capital: { name: "Kyoto", coords: [135.77, 35.01] }, territory: ["Japan"] },
  { id: "japan", name: "Empire of Japan", era: "1868–1947 AD", start: 1868, end: 1947,
    blurb: "Meiji modernization and a rising Pacific power.",
    capital: { name: "Tokyo", coords: [139.69, 35.69] },
    territory: ["Japan", "South Korea", "North Korea", "Taiwan"] },
  { id: "silla", name: "Silla", era: "57 BC–935 AD", start: -57, end: 935,
    blurb: "Golden crowns and the kingdom that unified the peninsula.",
    capital: { name: "Gyeongju", coords: [129.22, 35.86] }, territory: ["South Korea", "North Korea"] },
  { id: "goryeo", name: "Goryeo", era: "918–1392 AD", start: 918, end: 1392,
    blurb: "Celadon ware and the name that became 'Korea'.",
    capital: { name: "Kaesong", coords: [126.55, 37.97] }, territory: ["South Korea", "North Korea"] },
  { id: "khmer", name: "Khmer Empire", era: "802–1431 AD", start: 802, end: 1431,
    blurb: "Angkor Wat and a hydraulic city of a million souls.",
    capital: { name: "Angkor", coords: [103.87, 13.41] },
    territory: ["Cambodia", "Thailand", "Laos", "Vietnam"] },
  { id: "pagan", name: "Pagan Kingdom", era: "849–1297 AD", start: 849, end: 1297,
    blurb: "A plain of two thousand Buddhist temples.",
    capital: { name: "Bagan", coords: [94.86, 21.17] }, territory: ["Myanmar"] },
  { id: "sukhothai", name: "Sukhothai Kingdom", era: "1238–1438 AD", start: 1238, end: 1438,
    blurb: "The 'dawn of happiness' and the first Thai script.",
    capital: { name: "Sukhothai", coords: [99.82, 17.02] }, territory: ["Thailand"] },
  { id: "ayutthaya", name: "Ayutthaya Kingdom", era: "1351–1767 AD", start: 1351, end: 1767,
    blurb: "A glittering river capital that dazzled European envoys.",
    capital: { name: "Ayutthaya", coords: [100.58, 14.35] }, territory: ["Thailand", "Laos", "Cambodia"] },
  { id: "srivijaya", name: "Srivijaya", era: "671–1377 AD", start: 671, end: 1377,
    blurb: "Maritime Buddhist empire commanding the Malacca Strait.",
    capital: { name: "Palembang", coords: [104.75, -2.99] }, territory: ["Indonesia", "Malaysia"] },
  { id: "majapahit", name: "Majapahit Empire", era: "1293–1527 AD", start: 1293, end: 1527,
    blurb: "Java's golden thalassocracy across the archipelago.",
    capital: { name: "Trowulan", coords: [112.38, -7.55] }, territory: ["Indonesia", "Malaysia", "Brunei"] },
  { id: "champa", name: "Champa", era: "192–1832 AD", start: 192, end: 1832,
    blurb: "Hindu-Buddhist kingdom of brick towers along the coast.",
    capital: { name: "Mỹ Sơn", coords: [108.12, 15.76] }, territory: ["Vietnam"] },
  { id: "daiviet", name: "Đại Việt", era: "968–1804 AD", start: 968, end: 1804,
    blurb: "The enduring Vietnamese state that repelled Mongol fleets.",
    capital: { name: "Thăng Long", coords: [105.85, 21.03] }, territory: ["Vietnam"] },

  // ---- The Americas ----
  { id: "maya", name: "Maya Civilization", era: "c. 2000 BC–1500 AD", start: -2000, end: 1500,
    blurb: "Astronomers and pyramid-builders of the rainforest lowlands.",
    capital: { name: "Chichen Itza", coords: [-88.57, 20.68] },
    territory: ["Mexico", "Guatemala", "Belize", "Honduras"] },
  { id: "aztec", name: "Aztec Empire", era: "1428–1521 AD", start: 1428, end: 1521,
    blurb: "Tenochtitlan, the island capital in the Valley of Mexico.",
    capital: { name: "Tenochtitlan", coords: [-99.13, 19.43] }, territory: ["Mexico"] },
  { id: "nortechico", name: "Norte Chico", era: "c. 3500–1800 BC", start: -3500, end: -1800,
    blurb: "One of the oldest civilizations in the Americas.",
    capital: { name: "Caral", coords: [-77.52, -10.89] }, territory: ["Peru"] },
  { id: "inca", name: "Inca Empire", era: "1438–1533 AD", start: 1438, end: 1533,
    blurb: "Cusco, Machu Picchu, and roads across the Andes.",
    capital: { name: "Cusco", coords: [-71.97, -13.52] },
    territory: ["Peru", "Bolivia", "Ecuador", "Chile", "Colombia"] },
  { id: "tiwanaku", name: "Tiwanaku", era: "c. 300–1000 AD", start: 300, end: 1000,
    blurb: "High-altitude civilization on the shores of Lake Titicaca.",
    capital: { name: "Tiwanaku", coords: [-68.67, -16.55] }, territory: ["Bolivia", "Peru", "Chile"] },
  { id: "mississippian", name: "Mississippian Culture", era: "c. 800–1600 AD", start: 800, end: 1600,
    blurb: "Mound-builders of Cahokia, a city rivaling medieval London.",
    capital: { name: "Cahokia", coords: [-90.06, 38.66] }, territory: ["United States of America"] },
  { id: "puebloan", name: "Ancestral Puebloans", era: "c. 100–1300 AD", start: 100, end: 1300,
    blurb: "Cliff palaces and great houses of the desert Southwest.",
    capital: { name: "Chaco Canyon", coords: [-107.96, 36.06] }, territory: ["United States of America"] },
  { id: "muisca", name: "Muisca Confederation", era: "c. 600–1600 AD", start: 600, end: 1600,
    blurb: "Goldsmiths whose El Dorado ritual lured the conquistadors.",
    capital: { name: "Bacatá", coords: [-74.07, 4.71] }, territory: ["Colombia"] }
];

// English Wikipedia article titles (where they differ from the display name).
// Used to lazily fetch a thumbnail + summary and to build outbound links.
(function () {
  const WIKI = {
    babylon: "Babylonia", achaemenid: "Achaemenid Empire", parthia: "Parthian Empire",
    sassanid: "Sasanian Empire", hittite: "Hittites", carthage: "Ancient Carthage",
    almoravid: "Almoravid dynasty", ashanti: "Ashanti Empire", minoan: "Minoan civilization",
    macedon: "Macedonia (ancient kingdom)", etruscan: "Etruscan civilization",
    hispania: "Hispania", xiongnu: "Xiongnu", sogdiana: "Sogdia",
    indus: "Indus Valley Civilisation", ghaznavid: "Ghaznavids",
    qin: "Qin dynasty", han: "Han dynasty", tang: "Tang dynasty", heian: "Heian period",
    pagan: "Pagan kingdom", majapahit: "Majapahit", maya: "Maya civilization",
    nortechico: "Caral–Supe civilization", mississippian: "Mississippian culture",
    muisca: "Muisca", kievan: "Kievan Rus'", greece: "Classical Greece"
  };

  // Curated hero imagery: the Wikipedia article whose LEAD IMAGE best evokes
  // the empire (monuments over flags and maps). Fetched via the same summary
  // API, so no hand-crafted image URLs to rot. Empires not listed fall back
  // to their own article's lead image.
  const IMAGES = {
    sumer: "Ziggurat of Ur",
    babylon: "Ishtar Gate",
    assyria: "Lamassu",
    achaemenid: "Gate of All Nations",
    sassanid: "Taq Kasra",
    umayyad: "Umayyad Mosque",
    hittite: "Hattusa",
    byzantine: "Hagia Sophia",
    ottoman: "Süleymaniye Mosque",
    egypt: "Great Pyramid of Giza",
    ptolemaic: "Lighthouse of Alexandria",
    kush: "Nubian pyramids",
    aksum: "Obelisk of Axum",
    ethiopia: "Lalibela",
    carthage: "Carthage",
    almoravid: "Koutoubia Mosque",
    almohad: "Giralda",
    mali: "Great Mosque of Djenné",
    benin: "Benin Bronzes",
    ashanti: "Golden Stool",
    zimbabwe: "Great Zimbabwe",
    minoan: "Knossos",
    greece: "Parthenon",
    macedon: "Alexander Mosaic",
    rome: "Colosseum",
    gaul: "Vercingetorix",
    carolingian: "Palatine Chapel, Aachen",
    hre: "Aachen Cathedral",
    napoleon: "Arc de Triomphe",
    prussia: "Brandenburg Gate",
    spanish: "El Escorial",
    british: "Palace of Westminster",
    kievan: "Saint Sophia Cathedral, Kyiv",
    tsardom: "Saint Basil's Cathedral",
    russian: "Winter Palace",
    ussr: "Moscow Kremlin",
    mongol: "Genghis Khan",
    timurid: "Registan",
    indus: "Mohenjo-daro",
    maurya: "Sanchi",
    mughal: "Taj Mahal",
    qin: "Terracotta Army",
    han: "Great Wall of China",
    tang: "Giant Wild Goose Pagoda",
    heian: "Byōdō-in",
    silla: "Bulguksa",
    khmer: "Angkor Wat",
    pagan: "Bagan",
    sukhothai: "Sukhothai Historical Park",
    ayutthaya: "Ayutthaya Historical Park",
    champa: "Mỹ Sơn",
    maya: "Chichen Itza",
    aztec: "Templo Mayor",
    nortechico: "Caral",
    inca: "Machu Picchu",
    tiwanaku: "Gate of the Sun",
    mississippian: "Cahokia",
    puebloan: "Mesa Verde National Park",
    muisca: "Muisca raft"
  };

  window.EMPIRES.forEach(e => {
    e.wiki = WIKI[e.id] || e.name;
    e.imageWiki = IMAGES[e.id] || null;
  });
})();
